# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: baidooelton76@gmail.com
author_name: Elton Baidoo
contract_name: ogc_vault
deployment_language: python
preset_name: starter
project_name: ogc-contracts

