name: OGC CI

on:
  push:
    branches: [ main, develop, ci-runner ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install pipx and AlgoKit
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install algokit==2.9.0
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Verify AlgoKit installation
      run: algokit --version
      
    - name: Start LocalNet
      run: |
        algokit localnet start
        sleep 10  # Give LocalNet time to fully start
        
    - name: Install Poetry
      run: |
        python -m pip install poetry==1.8.3
        poetry --version
        
    - name: Install dependencies
      working-directory: ogc-contracts/projects/ogc-contracts
      run: |
        poetry install --no-interaction --no-root
        
    - name: Build contracts
      working-directory: ogc-contracts/projects/ogc-contracts
      run: |
        poetry run python working_vault.py
        ls -la artifacts/working_vault/ || echo "Artifacts directory not found"
        
    - name: Run tests
      working-directory: ogc-contracts/projects/ogc-contracts
      run: |
        poetry run python test_vault.py
        
    - name: Run OGC demo
      working-directory: ogc-contracts/projects/ogc-contracts
      run: |
        poetry run python ogc_demo.py
        
    - name: Stop LocalNet
      if: always()
      run: algokit localnet stop